version: "3.7"
services:
  php:
    image: castorland/php8.0-apache-laravel-root
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - .:/var/www/
    environment:
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
    container_name: timeoff-web
    security_opt:
      - no-new-privileges:true
    labels:
      # Enable this container to be mapped by traefik
      # For more information, see: https://docs.traefik.io/providers/docker/#exposedbydefault
      - "traefik.enable=true"
      # URL to reach this container
      - "traefik.http.routers.timeoff.rule=Host(`timeoff.local.test`)"
      # Activation of TLS
      - "traefik.http.routers.timeoff.tls=true"
      # If port is different than 80, use the following service:
      # - "traefik.http.services.<service_name>.loadbalancer.server.port=<port>"
    networks:
      - proxy
    expose:
      - "80"
      - "443"

  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped
    volumes:
      - db-vol:/var/lib/mysql
    command:
      [
          "mysqld",
          "--character-set-server=utf8mb4",
          "--collation-server=utf8mb4_unicode_ci",
      ]
    container_name: timeoff-db
    cap_add:
      - SYS_NICE
    expose:
      - "3306"
    networks:
      - proxy

networks:
  proxy:
    external: true

volumes:
  db-vol:
